name: Deploy MkDocs site

on:
  push:
    branches:
      - main  # Cambia se il tuo branch principale ha un altro nome (es: "master").

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install mkdocs-material  # Installa il tema Material per MkDocs

    - name: Build site
      run: |
        mkdocs build  # Genera i file del sito statico

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site  # La directory generata da "mkdocs build"